### ISSUE TITLE
How to run this to reproduce Table 1 results?

### ISSUE THREAD

**Issue by hughperkins** [jacobandreas/concepts#1]
Hi Jacob,

Awesome paper :)

Quite hard to figure out how to run this :)

- it looks like `cls.py` is the entry point, and `ClsModel` is the model that corresponds to the L3 "Learning with latent language" paper Table 1, is this a fair impression?
- I've tried running with:

```
python cls.py -train -n_epochs 10000
```
which gives outputs like:

```
[iter]    774
[loss]    10.2767
[trn_acc] 0.9700
[val_acc] 0.4980
[val_same_acc] 0.5280
[val_mean_acc] 0.5130
```

This looks like the results of training the interpretation model, is that right?

- How can I train in addition the proposal model?
- How can I train and run the full model, as in Table 1?

**Comment by jacobandreas** [comment]
Look at `exp/cls_*`---has configs for all the experiments.

**Comment by hughperkins** [comment]
Ok. Don't suppose ... what is the meaning of the names of the various scripts like 'cls_ex', 'cls_hint', 'cls_joint', 'cls_vis', etc?

**Comment by jacobandreas** [comment]
Sorry, bad names :). `ex` is Meta, `gold` is ground-truth descriptions, `hint` is L^3, `joint` is Meta+Joint, `sim` is another baseline that didn't make it into the paper, and `vis` is just visualization. I never got around to cleaning up the multitask baselines but let me know if you need those.

For the other two experiments, evaluation is done in a different script from training; those have the _eval suffix.

**Comment by hughperkins** [comment]
Awesome, thanks! :)
