### ISSUE TITLE
Code to generate additional shapeworld data?

### ISSUE THREAD

**Issue by hughperkins** [jacobandreas/concepts#3]
Hi Jacob,

Really like your shapeworld dataset. Question: how can I go about creating additional data, potentially with tweaked characteristics, eg number of distractors etc?

Hugh

**Comment by jacobandreas** [comment]
This all comes from Alex Kuhnle's ShapeWorld dataset (https://github.com/AlexKuhnle/ShapeWorld) which has lots of documentation about how to configure the environments and captions.

**Comment by hughperkins** [comment]
Ok, awesome. Thanks! :)

**Comment by hughperkins** [comment]
Hi, related question: don't suppose ... what command-line and configuration file(s) did you use to generate the data used for the L3 paper?

**Comment by hughperkins** [comment]
(Also, which git commit hash did you use please?)
