### ISSUE TITLE
Why is the size of the featurized images 4608, and not either 8192 or 2048?

### ISSUE THREAD

**Issue by hughperkins** [jacobandreas/concepts#4]
Hi Jacob,

Working my way slowly through L3 :)  It looks like the featurized inputs are vectors of length 4608?

```
In [1]: import numpy as np

In [2]: d = np.load('train/inputs.feats.npy')

In [3]: d.shape
Out[3]: (9000, 4608)
```

However, looking at VGG16, it seems to me to look like it consists of three types of layers:
- max-pooling, which halves the width and the height
- relu, which doesnt change any dimension
- padded conv, which also doesnt change the width or the height; and fixes the channels to an absolute number

Depending on whether we use the maxpooling after the final conv, there are either 4 max-poolings, or 5, meaning that the width and height will each be divided either by 2^4 = 16 or 2^5 = 32?  The number of channels in either case is set by the final conv, which is 512?

Then, given an input that is 3 x 64 x 64, the output will be either:

- 512 * 4 * 4 (if we ignore the pooling after the final conv), or
- 512 * 2 * 2 (if we include it)

Then, the flattened vector size in each case would be 8192 or 2048?

It looks like in order to obtain a size of 4608, if we assume there are 512 channels, we'd need a final output dimension of 512 x 3 x 3?

What am I missing in the above analysis?

**Comment by jacobandreas** [comment]
added the script I used to generate them under `extras/featurize.py`

**Comment by jacobandreas** [comment]
(Hopefully that clears things up---I haven't actually had time to re-run it and check the sizes. The model is from http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz and the inputs are the result of the generate script I sent you earlier.)

**Comment by hughperkins** [comment]
Awesome, thanks! :)
