### ISSUE TITLE
Reproduce L3 PbD results

### ISSUE THREAD

**Issue by jayelm** [jacobandreas/concepts#5]
Hi Jacob,

Which `exp/*` directory reproduces the 80 Val, 76 Test L3 programming by demonstration results? Haven't been able to find the numbers in any of the `train.out`s.

Thanks!

**Comment by jacobandreas** [comment]
https://github.com/jacobandreas/l3/blob/master/exp/pbd_hint_eval/eval.out
(sorry about the terrible names)
